# Generated by Django 4.2.15 on 2024-08-29 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedded_code', models.CharField(max_length=500)),
                ('add_date', models.DateTimeField(verbose_name='date added')),
                ('dish_name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('menu_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('ward', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.dish')),
            ],
        ),
    ]
