# Generated by Django 4.2.15 on 2024-08-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='vote_like',
            field=models.IntegerField(default=0),
        ),
    ]
