# Generated by Django 4.2.15 on 2024-09-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_dish_vote_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
